gremlin.graph=org.apache.tinkerpop.gremlin.tinkergraph.structure.TinkerGraph
# ANY: accept any object as a vertex/edge id (including strings). Our
# headache GraphSchema uses string ids.
gremlin.tinkergraph.vertexIdManager=ANY
gremlin.tinkergraph.edgeIdManager=ANY
gremlin.tinkergraph.vertexPropertyIdManager=ANY
